### ISSUE TITLE
License name?

### ISSUE THREAD

**Issue by Ambrevar** [stylewarning/computable-reals#2]
I'm in the process of packaging this library for Guix, but I'm not sure about the license name since it seems home-baked.
Which license name (or equivalent) should I specify?

**Comment by stylewarning** [comment]
Unfortunately the license doesn't have a name. It is "custom" from the original author, Michael Stoll. I wish I could say "it's basically BSD 2-clause", but it's not. I think if we contacted Michael Stoll, he might be willing to change it for us.

**Comment by Ambrevar** [comment]
Do you have his contact?

**Comment by stylewarning** [comment]
@Ambrevar His contact info is [here](http://www.mathe2.uni-bayreuth.de/stoll/index.html). If he relicenses it, do make a PR!

**Comment by Ambrevar** [comment]
Thanks, I've contacted him.

**Comment by Ambrevar** [comment]
Great news, Michael has relicensed his project under BSD-3 :)

See the beginning of the file reals.lisp that is available on

				http://www.mathe2.uni-bayreuth.de/stoll/programs/index.html 

Robert, can you update this repository to reflect the changes?

**Comment by stylewarning** [comment]
Yes, will do.

Thanks!

**Comment by stylewarning** [comment]
Done! https://github.com/stylewarning/computable-reals/commit/fdc73d75e79d0a4ce6d01c822c950ae2eb137d39

Thanks for helping!

**Comment by Ambrevar** [comment]
Thanks for updating!
